{
 "title": "ViaIpe Dashboard",
 "tags": [
  "viaipe",
  "monitoring"
 ],
 "refresh": "10s",
 "panels": [
  {
   "title": "Disponibilidade Média (%)",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  timestamp AS time,\r\n  availability AS value,\r\n  client AS metric\r\nFROM viaipe_metrics\r\nWHERE (availability >= 70)::int = 1\r\nORDER BY timestamp;\r\n"
    }
   ]
  },
  {
   "title": "Consumo de Banda Média (Mbps)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  timestamp AS time,\r\n  (avg_bandwidth / 1000000) AS value,\r\n  client AS metric\r\nFROM viaipe_metrics\r\nWHERE (avg_bandwidth / 1000000) >= 200\r\nORDER BY timestamp;\r\n"
    }
   ]
  },
  {
   "title": "Qualidade Média",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  timestamp AS time,\r\n  LEAST(quality, 100) AS value,\r\n  client AS metric\r\nFROM viaipe_metrics\r\nWHERE LEAST(quality, 100) >= 85\r\nORDER BY timestamp;\r\n\r\n\r\n"
    }
   ]
  },
  {
   "title": "Últimos Clientes Monitorados",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT DISTINCT ON (client) client, availability, avg_bandwidth, quality FROM viaipe_metrics ORDER BY client, timestamp DESC;"
    }
   ]
  }
 ]
}